//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kalkulator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kalkulator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///ESOB 1450 132,58 130,68 129,35 128,07 126,97 126,10 124,85
        ///ESOB 2900 135,60 133,43 131,61 130,27 129,18 128,12 127,06
        ///ESCC 1450 132,74 131,20 129,77 128,46 127,38 126,57 125,46
        ///ESCC 2900 135,93 133,82 132,23 130,77 129,86 128,80 127,75
        ///ESCCI 1450 136,67 134,60 133,44 132,30 131,00 130,32 128,98
        ///ESCCI 2900 139,45 136,53 134,91 133,69 132,65 131,34 129,83
        ///MS-V 2900 138,19 135,41 134,89 133,95 133,43 131,87 130,37
        ///MSS 2900 134,31 132,43 130,94 128,79 127,27 125,22 123,84.
        /// </summary>
        public static string ConstantC {
            get {
                return ResourceManager.GetString("ConstantC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap greenV {
            get {
                object obj = ResourceManager.GetObject("greenV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oznaczenia rodzaju pompy:
        ///Pompa do wody z wlotem osiowym i korpusem łoży­
        ///skowym (ESOB).
        ///Monoblokowa pompa do wody z wlotem osiowym 
        ///(ESCC).
        ///Monoblokowa pompa do wody z wlotem osiowymin- 
        ///line(ESCCi).
        ///Pionowa wielostopniowa pompa do wody (MS-V).
        ///Wielostopniowa głębinowa pompa do wody (MSS)..
        /// </summary>
        public static string Pomoc {
            get {
                return ResourceManager.GetString("Pomoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap redX {
            get {
                object obj = ResourceManager.GetObject("redX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
